### ISSUE TITLE
Can barcodes of split reads, chimeric reads and single split reads be reported?

### ISSUE THREAD

**Issue by jpcartailler** [AstraZeneca/detectIS#2]
Greetings and thank you for making this workflow available for others to use.

We've successfully run it, but we'd like to also further visualize the outputs. While the PAF alignment files are available, it would also be useful (in our opinion) to have the workflow return a list of the barcodes that are "matched" between the genome and insert. My Perl is *very rusty* but I think it would be performed in `verify_spreads_is()` and `verify_split_reads()` functions in `DetectSpltR.pm`? Any suggestions on how to proceed would be appreciated.

Also, do you accept pull requests? 

Thanks!

**Comment by luigra** [comment]
Hi PJ,

thanks for using the tool and giving us feedback. I am not 100% sure of your request: are you suggesting to save in a txt file the read names of the split reads?

**Comment by jpcartailler** [comment]
Indeed Luigi, the read names (not barcodes, sorry, was working on single cell at the same and ... ) of the split reads. I would like to be able to visualize them on IGV or some other genome browser. Thx! JP

**Comment by luigra** [comment]
Hi PJ,

I have changed the script and a file with the split reads is also generated. I will close the issue but please feel free to reopen it the changes I made are not correct or in line with your request.
