### ISSUE TITLE
Can't create Singularity container due to incomplete package configuration

### ISSUE THREAD

**Issue by don-philipe** [AstraZeneca/detectIS#4]
Hi there,

I have a problem creating the Singularity container. The `apt-get` installation process waits for user input on postfix configuration, but the user input is not accepted (see below). When adding the `dialog` package to the list of packages in `detectIS.rec`, a configuration dialog will be shown on console, but there is no option to select.

```
Preparing to unpack .../205-postfix_3.3.0-1ubuntu0.4_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Postfix Configuration
---------------------

Please select the mail server configuration type that best meets your needs.

 No configuration:
  Should be chosen to leave the current configuration unchanged.
 Internet site:
  Mail is sent and received directly using SMTP.
 Internet with smarthost:
  Mail is received directly using SMTP or by running a utility such
  as fetchmail. Outgoing mail is sent using a smarthost.
 Satellite system:
  All mail is sent to another machine, called a 'smarthost', for delivery.
 Local only:
  The only delivered mail is the mail for local users. There is no network.

  1. No configuration  3. Internet with smarthost  5. Local only
  2. Internet Site     4. Satellite system
General type of mail configuration: 1       
1
1
```

Would it be save to just remove the package `mailutils` from the package list in `detectIS.rec`, to avoid that buggy configuration? What limitations are to be expected without that package?

OS: Ubuntu 18.04
conda version : 4.7.12
detectIS: [bc08f49](https://github.com/AstraZeneca/detectIS/commit/bc08f4930781361a2ce8c5de556fc3d41ae428bb) (current master)

Thanks

**Comment by luigra** [comment]
Hi @don-philipe ,

thanks a lot for spotting this problem I did not have it before but I definitely have it now. 

There are no consequences in removing mailutils: I included it in the recipe because I thought it was potentially used by nextflow to manage the email notifications but I was wrong. I will remove it from the repository too.

Best wishes
Luigi
